### PR TITLE
Less Complicated Abstract Color Support

### PR DESCRIPTION
**Pull request by ciolt**
I spent a few hours on this, and I was able to finish creating a mini-stylesheet that allows for defining an accent color more easily, rather than applying the color to all the backgrounds, links, etc.

Other things done:
- update stuff
- make the design slightly better
- make the retweet dialog better #68 
- fix issues #66, #72, and #80

### CODE REVIEW

**Comment by dangeredwolf** [comment]
I can't tell, where is currentColor defined?

**Comment by ciolt** [comment]
currentColor is a CSS color value that basically inherits the value of the `color` property.

For example, `.blabla` here would have a red background.
```
.blabla {
    color: red;
    background: currentColor;
}
```

**Comment by ciolt** [comment]
I don't blame you for not knowing it, it's a pretty rare thing that I only found out after looking at Spotify's CSS files.

**Comment by dangeredwolf** [comment]
You've just introduced new UI bugs into the system. Lovely. I won't merge this until you fix the weirdness with the column options and stuff

**Comment by dangeredwolf** [comment]
derp accidentally clicked close

**Comment by ciolt** [comment]
What do you mean by "weirdness"? I haven't seen anything "weird" with the column options, they seem fine.

**Comment by ciolt** [comment]
I fixed the nasty merge conflicts @dangeredwolf

**Comment by dangeredwolf** [comment]
I cannot merge this until you either revert your changes to the column options tab or create a new solution which respects material design guidelines, works well in narrow column view, and works well in DM view (with more than 1 toolbar button)

Additionally, I cannot accept this build in its current form because it breaks the dark theme's accent colour and makes it way too bright, like the light theme. Never ever put theme-specific colours inside moderndeck.css. Ever. Period. Full stop. I had to rework the moderndeck code a bunch prior to 6.0's release to make moderndeck.css theme independent, and you've just undid all my work. Plus, yours has a TON of duplicate selectors, which is only going to hurt performance and memory footprint.

I'm going to try to implement your colour changes myself. If I get a build of it functioning properly with all of these colour changes, your branch will be closed, as I've already fixed the issues you've fixed in the main source tree.

**Comment by ciolt** [comment]
Since this is going _nowhere,_ I'll keep my fork ahead on this until further notice.

**Comment by dangeredwolf** [comment]
Some other things I've noticed have been messed up in your build:

Selected radio buttons do not have the accent colour applied, as it should according to material guidelines.

Not only do you have way way too many selectors for the theme colour, you're missing some of them, at least for dark mode, and its obviously coloured differently.

**Comment by dangeredwolf** [comment]
Sorry if I seem a bit pissy, it's just that I was annoyed after that argument. Regardless, if you fix these issues then I would be more than happy to have a look at it.

**Comment by ciolt** [comment]
### _Soon™_

**Comment by ciolt** [comment]
# The Briefing

>"Selected radio buttons do not have the accent colour applied, as it should according to material guidelines.”



## "Too Bright"

>"it breaks the dark theme's accent colour and makes it way too bright, like the light theme.”

The accent color is controlled by the user: the user's options are **First-Priority** and should be respected by the people giving them the option to change it. The dark theme's primary color can be easily changed through the ModernDeck settings to any colour: from Pink to Black. And for the true nerds, they can choose to make their dark theme look like this.

image

Because of the way things are (now) pre-configured on first launch, this is what simply ticking the "Dark" theme would look like on a first run.

image

>_"way too bright”_

## "Duplicate Selectors”

>"Not only do you have way way too many selectors for the theme colour, you're missing some of them, at least for dark mode, and its obviously coloured differently.”

**Q:** _"Why would you concatenate all references to the light/dark theme's accent colour into one selector that changes depending only on the extension's storage data?!"_

**A:** Because modularity is not achieved by repeating the same code over 8 times in a single (only one) file. This is only 1 (one!) file out of the whole thing, and I'm blamed for hard-coding colours into ModernDeck base styles, when they _should_ be in control of a thememaker or **THE USER.** [light.css]






image
image
image

## Complete Hypocrisy

>"Never ever put theme-specific colours inside moderndeck.css. Ever. Period. Full stop. I had to rework the moderndeck code a bunch prior to 6.0's release to make moderndeck.css theme independent, and you've just undid all my work.”

Revise this commit **thoroughly.** In order to not waste your time, there was not one, single, colour added that was not greyscale. The only types of "colours" that were added were dark shades, as in, the classic old `rgba(17, 17, 17, 0.45)`. This is coming from the world's leader in software code change tracking (git), not just me. https://github.com/dangeredwolf/ModernDeck/commit/9937cbffe73f0f794254da56b874d0753a13940e#diff-5c1983c7fac7f2127fcfd2a2da618444

Anything you suspected to be my fault is not, as every non-greyscale colour in [moderndeck.css](https://github.com/dangeredwolf/ModernDeck/blob/master/ModernDeck/sources/moderndeck.css) has been put there by someone else than me.

>"...duplicate selectors [are] only going to hurt performance and memory footprint.”

Repeating these 6 lines of code over 40 times simply to apply the same bluish cyan colour hurts performance and _ESPECIALLY_ memory footprint.

```css
#tweetdeck-element {
    color:bluish cyan;
}
#another-tweetdeck-element-that-could-be-grouped-to-save-memory-space-but-isnt_who-knows-why {
    color:bluish cyan, but 0.1% darker;
}
```

>"The settings view is completely messed up in terms of positioning, including all previous alignments, which make it look more like a 90s webpage than a modern web app in 2016”

[refer to the subtitle of this section]

The other day, I was called out by you because I coloured a selected circle, and you claimed it to be a FAB in the wrong place, with very wrong positioning.

Equally, I can call you out on the fact that there exists no so-called ```"positioning”``` or ```"alignments”``` here, because, all of the text in the content area is disproportionately misaligned.

And on top of that, if [Google didn't make it clear enough that text should be put left-to-right](https://material.google.com/style/typography.html), then you're essentially ruining Material Design's user experience factor. Why? Because _**ENGLISH**_ is read left-to-right, not right-to-left, or center-and-to-both-the-right-and-left (what the fuck?), so UIs in English are designed to have important content on the top left, less important on the bottom right.

image

And you compare me fixing a broken, _**INCONSISTENT**_ UI to a 90s website.

image

## Closing Notes

image

At the end of the day, at least Google could properly align things in the center.

image

**Comment by ciolt** [comment]
woof

**Comment by ciolt** [comment]
woof

**Comment by ciolt** [comment]
woof

**Comment by ciolt** [comment]
woof

**Pull request closed without merging**
